### ISSUE TITLE
Unable to run the module.

### ISSUE THREAD

**Issue by azaslonov** [Rodion93/win-cert#3]
Hi there, thank you for making the library!

Unfortunately, I wasn't able to run the module, always receive this error:

Error: Cannot find module './src/winCert'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\zaslo\Desktop\Cert\node_modules\win-cert\index.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

...and looks like the path indeed missing:
![image](https://user-images.githubusercontent.com/2320302/71058267-0ed31b00-2114-11ea-91a3-e3688676f09b.png)

**Comment by Rodion93** [comment]
> Hi there, thank you for making the library!
> 
> Unfortunately, I wasn't able to run the module, always receive this error:
> 
> Error: Cannot find module './src/winCert'
> at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
> at Function.Module._load (internal/modules/cjs/loader.js:507:25)
> at Module.require (internal/modules/cjs/loader.js:637:17)
> at require (internal/modules/cjs/helpers.js:22:18)
> at Object. (C:\Users\zaslo\Desktop\Cert\node_modules\win-cert\index.js:3:18)
> at Module._compile (internal/modules/cjs/loader.js:689:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
> at Module.load (internal/modules/cjs/loader.js:599:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
> at Function.Module._load (internal/modules/cjs/loader.js:530:3)
> 
> ...and looks like the path indeed missing:
> ![image](https://user-images.githubusercontent.com/2320302/71058267-0ed31b00-2114-11ea-91a3-e3688676f09b.png)

Thanks, I updated the library. Please re-add/update the library (version - 0.1.2)

**Comment by azaslonov** [comment]
Thanks for quick turnaround.
